save-data:
  transaction_id: "$.context.transaction_id"
  message_id: "$.context.message_id"
  items: "$.message.order.providers[*].items[*]"
  item: "$.message.order.providers[0].items[0]"
  selected_provider: "$.message.order.provider"
  Ekyc_details_form_cc: "$..form.url"
  form_id: "$..form.id"